### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by MatzeMuc86** [jsiegenthaler/hueget#3]
I like the tool a lot and use it since quite a while to operate my hue lights via shelly switches - just perfect, fast and reliable!

As I have to migrate my base Linux the tool is running on, I thought about why not having this app running in a docker image independently?Maybe this is a nice idea as a new way of installation.

**Comment by jsiegenthaler** [comment]
Sorry but I do not use Docker and I have zero knowledge of Docker. If you know about Docker feel free to contribute to this project.

**Comment by MatzeMuc86** [comment]
I got a working solution for docker this evening. I am not an expert at all and port, IP and api key are static.
Not sure if this non-expert early setup is wanted. I could add it to the docu of setup if you want; up to you!

**Comment by jsiegenthaler** [comment]
Feel free to make a PR and contribute

**Comment by jsiegenthaler** [comment]
Closing this issue as the OP has not responded. And I have zero knowledge of Docker.
