### ISSUE TITLE
Dimm up/down a light/group

### ISSUE THREAD

**Issue by betsim** [jsiegenthaler/hueget#5]
It would be nice to have the ability to dimm a light or a group (without setting 'bri' to an explicit value; just increase/decrease its actual value)

**Comment by jsiegenthaler** [comment]
You can use the `transitiontime` and `bri_inc` arguments to set the transition as you wish. See the API documentation here https://developers.meethue.com/develop/hue-api/lights-api/

**Comment by jsiegenthaler** [comment]
I'll close this issue as the functionality already exists
