### ISSUE TITLE
toggle hue lights

### ISSUE THREAD

**Issue by Orca75** [jsiegenthaler/hueget#6]
**Is your feature request related to a problem? Please describe:**
It's an addition, if you want to toggle a light from a dummy shelly button, that supports only http get and doesn't know if the light is on or off.

**Describe the solution you'd like:**
I changed your file that way, that it is now possible to toggle a light

curl -k http://localhost:3000/api/<removed>/lights/1/toggle
[{"success":{"/lights/1/state/on":true}}]

**Describe alternatives you've considered:**

**Additional context:**
Attached the file I use now. Probably it could be done easier if some parts would be functions. (so it's redundant)

[hueget_toggle.js.txt](https://github.com/jsiegenthaler/hueget/files/13629178/hueget_toggle.js.txt)

**Comment by jsiegenthaler** [comment]
Interesting approach, thanks. I'll add it in...

**Comment by jsiegenthaler** [comment]
Working on this now, but I'm adding the toggle function to both lights and groups. Same syntax

**Comment by jsiegenthaler** [comment]
Added in release v0.7.0

**Comment by BorghoutsR** [comment]
The toggle does not seem to work in 7.6.0;
{"error":"url syntax error, unknown command \"toggle\", expecting \"state\": \"/lights/7/toggle\""}

Everything else works like a charm.

**Comment by jsiegenthaler** [comment]
Oops, dunno what happened there. I'll have a look

**Comment by jsiegenthaler** [comment]
Hmm. I just tried v0.7.6, running on my raspberry pi.
I used the syntax:
http://192.168.0.100:3000/api/myApiUsername/lights/31/toggle
and it worked perfectly, switching my light 31 on and then off (toggling) as it should

Post your full url for me to check (but hide your api username)
